- name: Acte 1 - Configuration d'interfaces sur csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false
  # Liste des tâches associées à notre Acte
  tasks:
    - name: Récupère la configuration
      # On indique le nom du module
      cisco.ios.ios_command:
        # On indique ensuite ces paramètres
        # Liste dans https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_command_module.html
        commands: show running-config
      # Register permet de récupérer le résultat de la commande
      # et de le mettre dans la variable config
      register: config

    - name: Enregistre la configuration
      # Module pour copier des fichiers
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
      copy:
        # Source : ce que l'on a récupéré dans config
        content: " {{ config.stdout[0] }}"
        # Nom du fichier, le terme entre accolade est une variable
        dest: "show_run_{{ inventory_hostname }}.txt"

    - name: Configuration de l'interface Gigabit 1
      cisco.ios.ios_l3_interfaces:
        config :
          - name: GigabitEthernet1
            ipv4:
#            description: "Interface par dhcp"
              - dhcp:
                  enable: true

    - name: Configuration de l'interface Gigabit 2
      cisco.ios.ios_l3_interfaces:
        config :
        - name: GigabitEthernet2
#        description: "Interface réseau 192.168.2.0/24"
          ipv4:
            - address: 192.168.2.1/24
        state: merged

    - name: Configuration de l'interface Gigabit 3
      cisco.ios.ios_l3_interfaces:
        config :
        - name: GigabitEthernet3
#        description: "Interface réseau 192.168.3.0/24"
          ipv4:
            - address: 192.168.3.1/24
        state: merged

    - name: Configuration de l'interface Gigabit 4
      cisco.ios.ios_l3_interfaces:
        config :
        - name: GigabitEthernet4
#        description: "Interface réseau 192.168.4.0/24"
          ipv4:
            - address: 192.168.4.1/24
        state: merged

    - name: Suppression du pool DHCP existant
      cisco.ios.ios_config:
        lines:
          - "no ip dhcp pool dhcp_lan"


    - name: Configuration du serveur DHCP
      cisco.ios.ios_config:
        lines:
          - "ip dhcp excluded-address 192.168.2.1"
          - "ip dhcp pool dhcp_lan"
          - "network 192.168.2.0 255.255.255.0"
          - "default-router 192.168.2.1"
          - "dns-server 10.250.250.12"

    
    - name: Configuration NAT outside
      cisco.ios.ios_config:
        lines:
          - "interface GigabitEthernet1"
          - "ip nat outside"
        parents: "interface GigabitEthernet1"

    - name: Configuration NAT inside
      cisco.ios.ios_config:
        lines:
          - "interface {{ item }}"
          - "ip nat inside"
        parents: "interface {{ item }}"
   
      loop:
        - "GigabitEthernet2"
        - "GigabitEthernet3"
        - "GigabitEthernet4"

    - name: Configuration ACL pour NAT dynamique
      cisco.ios.ios_config:
        lines:
          - "access-list 1 permit 192.168.0.0  0.0.255.255"
          - "ip nat inside source list 1 interface GigabitEthernet1 overload"

  
    - name: Configuration NAT statique
      cisco.ios.ios_config:
        lines:
          - "ip nat inside source static tcp 192.168.3.2 80 interface GigabitEthernet1 80"
          - "ip nat inside source static tcp 192.168.4.2 22 interface GigabitEthernet1 2222"
        parents:
          - "interface GigabitEthernet1"
        
- name: Acte 2 - essai serv_web
  hosts: serv_web
  become: yes
  gather_facts: false
  tasks:
    - name: Mise à jour du cache apt
      apt:
        update_cache: yes

    - name: Installation du paquet apache2
      apt:
        name: apache2
        state: present

    - name: Copie du répertoire site_web dans /var/www/html/
      copy:
        src: site_web/
        dest: /var/www/html/
        owner: www-data
        mode: "0600"

    - name: Redémarrage du service apache
      service:
        name: apache2
        enabled: yes
        state: restarted
